### ISSUE TITLE
'Go to previous' (backspace) not triggered on certain computing hardware

### ISSUE THREAD

**Issue by hnicke** [hnicke/sodalite#17]

**Comment by nfode** [comment]
You use the `curses.ascii.DEL` keycode, on my system the `curses.KEY_BACKSPACE` key code does its job an I can navigate back. If some systems need the del key and others need the backspace key we should add both.

**Comment by hnicke** [comment]
On my main workstation, it would only work with `curses.ascii.DEL`, so I decided to simply add `curses.ascii.DEL` as trigger.
