### ISSUE TITLE
Favour non hidden files and folders at initial key assignment

### ISSUE THREAD

**Issue by nfode** [hnicke/sodalite#59]
Currently hidden and non hidden files seem to be equal at the inital key assignment. It might be better to map first all available keys to the visible ones because it is more likely that a user visits these files and folders.

**Comment by hnicke** [comment]
Found this gem in the assignment logic, right before assignment takes place:
```python
# TODO fix
# entry_module.sort(new_entries)
```

**Comment by hnicke** [comment]
The entries now get sorted with these criteria: 1. hidden or non-hidden, 2. dir or file, 3. file name.
Non-hidden directories beginning with 'a' get assigned at first.
